CREATE DATABASE IF NOT EXISTS copa2026;
USE copa2026;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS selecoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(3) NOT NULL,
    bandeira_url VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS jogadores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    selecao_id INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    posicao VARCHAR(50),
    foto_url VARCHAR(255),
    codigo_figurinha VARCHAR(10) NOT NULL UNIQUE,
    FOREIGN KEY (selecao_id) REFERENCES selecoes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS usuario_figurinhas (
    usuario_id INT NOT NULL,
    jogador_id INT NOT NULL,
    quantidade INT DEFAULT 1,
    PRIMARY KEY (usuario_id, jogador_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (jogador_id) REFERENCES jogadores(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
